// Generated from the client's WhatsApp photo batch (imported 2026-09-15).
// provenance: "stock" = Elite Balaji's own slab/stock photo; "work" =
// Elite Balaji's own finished work; "idea" = a reference image the client
// forwarded, ALWAYS shown with an "Application idea" label and never as our work.
// Granite names were identified visually from our stock photos (user-approved,
// 2026-09-15) and carry a confirm-availability note wherever shown.

// "supply" = a supplier's lot photo the client shared (real material, not
// necessarily in our yard today).
export type Provenance = "stock" | "work" | "idea" | "supply";
export interface MediaItem {
  slug: string;
  title: string;
  alt: string;
  src: string;
  thumb: string;
  width: number;
  height: number;
  provenance: Provenance;
  categories: string[];
  productId?: string;
}

export const provenanceLabel: Record<Provenance, string> = {
  stock: "From our stock",
  work: "Our work",
  idea: "Application idea",
  supply: "Supplier lot photo",
};

export const mediaLibrary: MediaItem[] = [
  {"slug": "black-galaxy-slabs", "title": "Black Galaxy", "alt": "Polished black granite slabs with gold flecks in our yard", "src": "/media/client/granite/black-galaxy-slabs.jpg", "thumb": "/media/client/granite/black-galaxy-slabs-720.jpg", "width": 500, "height": 500, "provenance": "stock", "categories": ["granite"], "productId": "granite-black-galaxy"},
  {"slug": "black-galaxy-closeup", "title": "Black Galaxy, close-up", "alt": "Black granite with fine gold and copper flecks", "src": "/media/client/granite/black-galaxy-closeup.jpg", "thumb": "/media/client/granite/black-galaxy-closeup-720.jpg", "width": 600, "height": 800, "provenance": "stock", "categories": ["granite"], "productId": "granite-black-galaxy"},
  {"slug": "black-galaxy-macro", "title": "Black Galaxy, macro", "alt": "Black granite with bronze crystal flecks, macro view", "src": "/media/client/granite/black-galaxy-macro.jpg", "thumb": "/media/client/granite/black-galaxy-macro-720.jpg", "width": 682, "height": 682, "provenance": "stock", "categories": ["granite"], "productId": "granite-black-galaxy"},
  {"slug": "blue-pearl-closeup", "title": "Blue Pearl", "alt": "Dark granite with iridescent blue crystal patches", "src": "/media/client/granite/blue-pearl-closeup.jpg", "thumb": "/media/client/granite/blue-pearl-closeup-720.jpg", "width": 600, "height": 600, "provenance": "stock", "categories": ["granite"], "productId": "granite-blue-pearl"},
  {"slug": "tan-brown-slab", "title": "Tan Brown", "alt": "Polished brown and black granite slab", "src": "/media/client/granite/tan-brown-slab.jpg", "thumb": "/media/client/granite/tan-brown-slab-720.jpg", "width": 736, "height": 552, "provenance": "stock", "categories": ["granite"], "productId": "granite-tan-brown"},
  {"slug": "kondagattu-slabs", "title": "Kondagattu", "alt": "Stack of polished red-brown flecked granite slabs", "src": "/media/client/granite/kondagattu-slabs.jpg", "thumb": "/media/client/granite/kondagattu-slabs-720.jpg", "width": 1040, "height": 780, "provenance": "stock", "categories": ["granite"], "productId": "granite-kondagattu"},
  {"slug": "absolute-black-polished-slabs", "title": "Absolute Black, polished", "alt": "Stack of polished jet-black granite slabs", "src": "/media/client/granite/absolute-black-polished-slabs.jpg", "thumb": "/media/client/granite/absolute-black-polished-slabs-720.jpg", "width": 960, "height": 1280, "provenance": "stock", "categories": ["granite"], "productId": "granite-absolute-black"},
  {"slug": "blue-sapphire-slabs", "title": "Blue Sapphire", "alt": "Polished Blue Sapphire granite slabs, dark blue-grey, outdoors", "src": "/media/client/granite/blue-sapphire-slabs.jpg", "thumb": "/media/client/granite/blue-sapphire-slabs-720.jpg", "width": 1599, "height": 899, "provenance": "stock", "categories": ["granite"], "productId": "granite-blue-sapphire"},
  {"slug": "black-markino-slab", "title": "Black Markino", "alt": "Black granite slab with bold white wave veins", "src": "/media/client/granite/black-markino-slab.jpg", "thumb": "/media/client/granite/black-markino-slab-720.jpg", "width": 1200, "height": 900, "provenance": "stock", "categories": ["granite"], "productId": "granite-black-markino"},
  {"slug": "absolute-black-leathered-slab", "title": "Absolute Black, leathered", "alt": "Absolute Black granite slab with a leathered finish", "src": "/media/client/granite/absolute-black-leathered-slab.jpg", "thumb": "/media/client/granite/absolute-black-leathered-slab-720.jpg", "width": 750, "height": 1334, "provenance": "stock", "categories": ["granite"], "productId": "granite-absolute-black-leathered"},
  {"slug": "steel-grey-slab", "title": "Steel Grey", "alt": "Polished grey speckled granite slab", "src": "/media/client/granite/steel-grey-slab.jpg", "thumb": "/media/client/granite/steel-grey-slab-720.jpg", "width": 1199, "height": 847, "provenance": "stock", "categories": ["granite"], "productId": "granite-steel-grey"},
  {"slug": "absolute-black-leathered-countertop", "title": "Leathered black countertop", "alt": "Close-up of a leathered black granite countertop", "src": "/media/client/granite/absolute-black-leathered-countertop.jpg", "thumb": "/media/client/granite/absolute-black-leathered-countertop-720.jpg", "width": 1200, "height": 1600, "provenance": "stock", "categories": ["granite", "kitchen"], "productId": "granite-absolute-black-leathered"},
  {"slug": "granite-staircase", "title": "Granite staircase", "alt": "Entrance staircase finished in dark polished granite", "src": "/media/client/granite/granite-staircase.jpg", "thumb": "/media/client/granite/granite-staircase-720.jpg", "width": 922, "height": 1600, "provenance": "work", "categories": ["granite", "applications"]},
  {"slug": "white-slab-veined", "title": "White veined slab", "alt": "Large polished white slab with soft grey veining", "src": "/media/client/marble/white-slab-veined.jpg", "thumb": "/media/client/marble/white-slab-veined-720.jpg", "width": 1200, "height": 900, "provenance": "stock", "categories": ["marble"], "productId": "marble-premium-white"},
  {"slug": "white-slab-warehouse", "title": "White slab", "alt": "Polished white slab with light grey veins in a warehouse", "src": "/media/client/marble/white-slab-warehouse.jpg", "thumb": "/media/client/marble/white-slab-warehouse-720.jpg", "width": 1200, "height": 1600, "provenance": "stock", "categories": ["marble"], "productId": "marble-carrara-look"},
  {"slug": "engraved-rose-granite", "title": "Engraved rose motif", "alt": "Rose vine motif engraved into a black granite panel", "src": "/media/client/stonecraft/engraved-rose-granite.jpg", "thumb": "/media/client/stonecraft/engraved-rose-granite-720.jpg", "width": 900, "height": 1600, "provenance": "work", "categories": ["stonecraft", "engraving"]},
  {"slug": "house-name-plate", "title": "Engraved house name plate", "alt": "Black stone name plate with gold engraved border and Ganesha motif (customer names hidden)", "src": "/media/client/stonecraft/house-name-plate.jpg", "thumb": "/media/client/stonecraft/house-name-plate-720.jpg", "width": 1199, "height": 798, "provenance": "work", "categories": ["stonecraft", "engraving"]},
  {"slug": "welcome-sign", "title": "Welcome sign", "alt": "Arched black granite sign with gold engraved Welcome lettering and bird motifs", "src": "/media/client/stonecraft/welcome-sign.jpg", "thumb": "/media/client/stonecraft/welcome-sign-720.jpg", "width": 1199, "height": 761, "provenance": "work", "categories": ["stonecraft", "engraving"]},
  {"slug": "granite-bench-indoor", "title": "Granite bench", "alt": "Black granite bench with backrest indoors", "src": "/media/client/stonecraft/granite-bench-indoor.jpg", "thumb": "/media/client/stonecraft/granite-bench-indoor-720.jpg", "width": 1200, "height": 900, "provenance": "work", "categories": ["stonecraft", "furniture"]},
  {"slug": "granite-dining-table", "title": "Granite dining table", "alt": "Polished black granite dining table with stone pedestal base", "src": "/media/client/stonecraft/granite-dining-table.jpg", "thumb": "/media/client/stonecraft/granite-dining-table-720.jpg", "width": 1200, "height": 900, "provenance": "work", "categories": ["stonecraft", "furniture"]},
  {"slug": "granite-outdoor-table-set", "title": "Outdoor table set", "alt": "Black granite outdoor table with four stone stools", "src": "/media/client/stonecraft/granite-outdoor-table-set.jpg", "thumb": "/media/client/stonecraft/granite-outdoor-table-set-720.jpg", "width": 1199, "height": 899, "provenance": "work", "categories": ["stonecraft", "furniture"]},
  {"slug": "granite-garden-bench", "title": "Garden bench", "alt": "Black granite garden bench on a lawn", "src": "/media/client/stonecraft/granite-garden-bench.jpg", "thumb": "/media/client/stonecraft/granite-garden-bench-720.jpg", "width": 600, "height": 450, "provenance": "work", "categories": ["stonecraft", "furniture"]},
  {"slug": "tulsi-madam-engraved-black", "title": "Engraved tulsi madam", "alt": "Black granite tulsi madam with engraved deity panels", "src": "/media/client/stonecraft/tulsi-madam-engraved-black.jpg", "thumb": "/media/client/stonecraft/tulsi-madam-engraved-black-720.jpg", "width": 427, "height": 640, "provenance": "work", "categories": ["stonecraft", "devotional", "engraving"]},
  {"slug": "tulsi-madam-red-granite", "title": "Red granite tulsi madam", "alt": "Red and white granite tulsi madam with lotus crown", "src": "/media/client/stonecraft/tulsi-madam-red-granite.jpg", "thumb": "/media/client/stonecraft/tulsi-madam-red-granite-720.jpg", "width": 864, "height": 1152, "provenance": "work", "categories": ["stonecraft", "devotional"]},
  {"slug": "tulsi-madam-grey-granite", "title": "Grey granite tulsi madam", "alt": "Grey granite tulsi madam with lotus crown in a garden", "src": "/media/client/stonecraft/tulsi-madam-grey-granite.jpg", "thumb": "/media/client/stonecraft/tulsi-madam-grey-granite-720.jpg", "width": 736, "height": 1308, "provenance": "work", "categories": ["stonecraft", "devotional"]},
  {"slug": "pooja-unit-black-granite", "title": "Granite pooja unit", "alt": "Grey and black granite pooja unit with Om carving", "src": "/media/client/stonecraft/pooja-unit-black-granite.jpg", "thumb": "/media/client/stonecraft/pooja-unit-black-granite-720.jpg", "width": 720, "height": 960, "provenance": "work", "categories": ["stonecraft", "devotional"]},
  {"slug": "tulsi-madam-white-marble", "title": "White marble tulsi madam", "alt": "White marble tulsi madam with lotus petals and a tulsi plant", "src": "/media/client/stonecraft/tulsi-madam-white-marble.jpg", "thumb": "/media/client/stonecraft/tulsi-madam-white-marble-720.jpg", "width": 736, "height": 1386, "provenance": "work", "categories": ["stonecraft", "devotional"]},
  {"slug": "granite-bench-white", "title": "White granite bench", "alt": "Wavy white-grey granite garden bench", "src": "/media/client/stonecraft/granite-bench-white.jpg", "thumb": "/media/client/stonecraft/granite-bench-white-720.jpg", "width": 1200, "height": 1118, "provenance": "work", "categories": ["stonecraft", "furniture"]},
  {"slug": "idea-black-granite-kitchen", "title": "Black granite kitchen", "alt": "Modern kitchen with black granite counters and a white-veined black island", "src": "/media/client/ideas/idea-black-granite-kitchen.jpg", "thumb": "/media/client/ideas/idea-black-granite-kitchen-720.jpg", "width": 1196, "height": 1600, "provenance": "idea", "categories": ["kitchen", "applications"]},
  {"slug": "idea-white-island-kitchen", "title": "White stone kitchen island", "alt": "Bright kitchen with a white marble-look island", "src": "/media/client/ideas/idea-white-island-kitchen.jpg", "thumb": "/media/client/ideas/idea-white-island-kitchen-720.jpg", "width": 768, "height": 1024, "provenance": "idea", "categories": ["kitchen", "applications"]},
  {"slug": "idea-stone-vessel-basins", "title": "Stone vessel basins", "alt": "Carved natural stone vessel basins on display shelves", "src": "/media/client/ideas/idea-stone-vessel-basins.jpg", "thumb": "/media/client/ideas/idea-stone-vessel-basins-720.jpg", "width": 1200, "height": 1204, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-wc-basin-display", "title": "WC & basin display", "alt": "Row of wall-hung basins above one-piece WCs", "src": "/media/client/ideas/idea-wc-basin-display.jpg", "thumb": "/media/client/ideas/idea-wc-basin-display-720.jpg", "width": 833, "height": 776, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-sanitaryware-gallery", "title": "Sanitaryware gallery", "alt": "Sanitaryware showroom display with WCs and shower panels", "src": "/media/client/ideas/idea-sanitaryware-gallery.jpg", "thumb": "/media/client/ideas/idea-sanitaryware-gallery-720.jpg", "width": 1200, "height": 1600, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-marble-sink-counter", "title": "Marble counter with sink", "alt": "White marble counter with an undermount steel sink", "src": "/media/client/ideas/idea-marble-sink-counter.jpg", "thumb": "/media/client/ideas/idea-marble-sink-counter-720.jpg", "width": 701, "height": 1024, "provenance": "idea", "categories": ["kitchen"]},
  {"slug": "idea-black-sink-granite", "title": "Black sink on granite", "alt": "Black undermount sink and faucet set into dark granite", "src": "/media/client/ideas/idea-black-sink-granite.jpg", "thumb": "/media/client/ideas/idea-black-sink-granite-720.jpg", "width": 899, "height": 1599, "provenance": "idea", "categories": ["kitchen"]},
  {"slug": "idea-designer-basins-shelf", "title": "Designer basins", "alt": "Patterned and marble-look vessel basins on grey shelving", "src": "/media/client/ideas/idea-designer-basins-shelf.jpg", "thumb": "/media/client/ideas/idea-designer-basins-shelf-720.jpg", "width": 1200, "height": 900, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-basin-rack", "title": "Vessel basin rack", "alt": "Metal rack of assorted designer vessel basins", "src": "/media/client/ideas/idea-basin-rack.jpg", "thumb": "/media/client/ideas/idea-basin-rack-720.jpg", "width": 900, "height": 1600, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-floating-basin-shelves", "title": "Basins on floating shelves", "alt": "Designer vessel basins on floating wooden shelves", "src": "/media/client/ideas/idea-floating-basin-shelves.jpg", "thumb": "/media/client/ideas/idea-floating-basin-shelves-720.jpg", "width": 960, "height": 1440, "provenance": "idea", "categories": ["bathroom"]},
  {"slug": "idea-cnc-engraving", "title": "CNC stone cutting", "alt": "CNC machine cutting a motif into a stone slab", "src": "/media/client/ideas/idea-cnc-engraving.jpg", "thumb": "/media/client/ideas/idea-cnc-engraving-720.jpg", "width": 750, "height": 1125, "provenance": "idea", "categories": ["stonecraft-process"]},
  {"slug": "idea-hand-finishing", "title": "Hand finishing", "alt": "Craftsman hand-finishing a carved stone basin with a grinder", "src": "/media/client/ideas/idea-hand-finishing.jpg", "thumb": "/media/client/ideas/idea-hand-finishing-720.jpg", "width": 1200, "height": 1600, "provenance": "idea", "categories": ["stonecraft-process"]},
  {"slug": "silver-black-lappato-slabs", "title": "Silver Black, Lappato", "alt": "Stack of black granite slabs with a textured lappato finish in our yard", "src": "/media/client/granite/silver-black-lappato-slabs.jpg", "thumb": "/media/client/granite/silver-black-lappato-slabs-720.jpg", "width": 1280, "height": 960, "provenance": "stock", "categories": ["granite"], "productId": "granite-silver-black-lappato"},
  {"slug": "marvel-red-lappato-slab", "title": "Marvel Red, Lappato", "alt": "Red-brown granite slab with dark crystals and a lappato finish", "src": "/media/client/granite/marvel-red-lappato-slab.jpg", "thumb": "/media/client/granite/marvel-red-lappato-slab-720.jpg", "width": 1280, "height": 960, "provenance": "stock", "categories": ["granite"], "productId": "granite-marvel-red-lappato"},
  {"slug": "tan-brown-leathered-slab", "title": "Tan Brown, Leathered", "alt": "Black and brown granite slab with a textured leathered finish", "src": "/media/client/granite/tan-brown-leathered-slab.jpg", "thumb": "/media/client/granite/tan-brown-leathered-slab-720.jpg", "width": 1280, "height": 960, "provenance": "stock", "categories": ["granite"], "productId": "granite-tan-brown-leathered"},
  {"slug": "blue-pearl-leathered-slab", "title": "Blue Pearl, Leathered", "alt": "Blue-black granite slab with blue crystals and a textured leathered finish", "src": "/media/client/granite/blue-pearl-leathered-slab.jpg", "thumb": "/media/client/granite/blue-pearl-leathered-slab-720.jpg", "width": 1600, "height": 1200, "provenance": "stock", "categories": ["granite"], "productId": "granite-blue-pearl-leathered"},
  {"slug": "wooden-granite-lot-15", "title": "Wooden Granite, supplier lot", "alt": "Wood-grain sandstone slabs, lot 15: 305 × 74 cm, 34 pieces", "src": "/media/client/granite/wooden-granite-lot-15.jpg", "thumb": "/media/client/granite/wooden-granite-lot-15-720.jpg", "width": 1024, "height": 767, "provenance": "supply", "categories": ["granite"], "productId": "granite-wooden"},
  {"slug": "wooden-granite-lot-16", "title": "Wooden Granite, supplier lot", "alt": "Wood-grain sandstone slabs with orange banding, lot 16: 275 × 76 cm, 25 pieces", "src": "/media/client/granite/wooden-granite-lot-16.jpg", "thumb": "/media/client/granite/wooden-granite-lot-16-720.jpg", "width": 1024, "height": 768, "provenance": "supply", "categories": ["granite"], "productId": "granite-wooden"},
  {"slug": "wooden-granite-lot-13", "title": "Wooden Granite, supplier lot", "alt": "Red-brown wood-grain sandstone slabs, lot 13: 244 × 53 cm, 25 pieces", "src": "/media/client/granite/wooden-granite-lot-13.jpg", "thumb": "/media/client/granite/wooden-granite-lot-13-720.jpg", "width": 1024, "height": 767, "provenance": "supply", "categories": ["granite"], "productId": "granite-wooden"},
  {"slug": "wooden-granite-lot-09", "title": "Wooden Granite, supplier lot", "alt": "Wood-grain sandstone slabs, lot 09: 275 × 62 cm, 22 pieces", "src": "/media/client/granite/wooden-granite-lot-09.jpg", "thumb": "/media/client/granite/wooden-granite-lot-09-720.jpg", "width": 1024, "height": 767, "provenance": "supply", "categories": ["granite"], "productId": "granite-wooden"},
  {"slug": "wooden-granite-stack", "title": "Wooden Granite, supplier lot", "alt": "Stack of polished wood-grain slabs", "src": "/media/client/granite/wooden-granite-stack.jpg", "thumb": "/media/client/granite/wooden-granite-stack-720.jpg", "width": 1080, "height": 810, "provenance": "supply", "categories": ["granite"], "productId": "granite-wooden"},
  {"slug": "teakwood-granite-slab", "title": "Teakwood Granite", "alt": "Polished teakwood granite slab with swirling wood-grain pattern being unloaded", "src": "/media/client/granite/teakwood-granite-slab.jpg", "thumb": "/media/client/granite/teakwood-granite-slab-720.jpg", "width": 1080, "height": 608, "provenance": "stock", "categories": ["granite"], "productId": "granite-teakwood"},
  {"slug": "sandstone-granite-slab", "title": "Sandstone Granite", "alt": "Light golden sandstone granite slab with soft horizontal banding under a shed", "src": "/media/client/granite/sandstone-granite-slab.jpg", "thumb": "/media/client/granite/sandstone-granite-slab-720.jpg", "width": 960, "height": 1280, "provenance": "stock", "categories": ["granite"], "productId": "granite-sandstone"},
];

/** One media item by slug. Defined here rather than re-declared per page. */
export const bySlug = (slug: string) => mediaLibrary.find((m) => m.slug === slug)!;

export const mediaIn = (category: string, provenance?: Provenance) =>
  mediaLibrary.filter((m) => m.categories.includes(category) && (!provenance || m.provenance === provenance));
